title: 'Nathan Dai'
copyright_time: 2015-2020
author:
  name: Nathan Dai
  email: daizheng@dashwood.xyz
description: > # this means to ignore newlines until "show_subtitle:"
  Invictus Maneo!

show_subtitle: true # set true to show subtitle on the homepage

permalink: /:title.html

# date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
glance:
  date_format: "%Y-%m-%d"

# Build settings
theme: glance

plugins:
 - jekyll-feed
 - jekyll-seo-tag
#  - jekyll-paginate
